import { StoreState } from "./types";

export const defaultStoreState: StoreState = {
  categories: [
    {
      id: "premium-dry",
      slug: "premium-dry",
      name: "Racao Seca Premium",
      description: "Linhas premium para nutricao diaria equilibrada.",
    },
    {
      id: "natural",
      slug: "natural",
      name: "Racao Natural",
      description: "Formula sem corantes artificiais e com ingredientes naturais.",
    },
    {
      id: "wet-food",
      slug: "wet-food",
      name: "Sachês e Umidos",
      description: "Opcoes umidas para complementar a alimentacao.",
    },
  ],
  products: [
    {
      id: "golden-adulto-frango-15kg",
      slug: "golden-adulto-frango-15kg",
      categoryId: "premium-dry",
      name: "Golden Formula Adulto Frango e Arroz 15kg",
      brand: "Golden",
      lifeStage: "adult",
      sizeProfile: "medium",
      flavor: "Frango e arroz",
      priceCents: 18990,
      compareAtCents: 20990,
      weightKg: 15,
      stock: 18,
      featured: true,
      active: true,
      imageUrl: "/store-app/assets/golden-adulto-frango-15kg.jpg",
      highlights: ["Alta digestibilidade", "Sem corantes artificiais", "Omega 3 e 6"],
    },
    {
      id: "premier-puppy-frango-12kg",
      slug: "premier-puppy-frango-12kg",
      categoryId: "premium-dry",
      name: "Premier Formula Filhotes Frango 12kg",
      brand: "Premier",
      lifeStage: "puppy",
      sizeProfile: "medium",
      flavor: "Frango",
      priceCents: 22490,
      weightKg: 12,
      stock: 10,
      featured: true,
      active: true,
      imageUrl: "/store-app/assets/premier-puppy-frango-12kg.jpg",
      highlights: ["DHA para desenvolvimento", "Enriquecida com vitaminas", "Proteina de alta qualidade"],
    },
    {
      id: "nd-prime-adulto-cordeiro-10kg",
      slug: "nd-prime-adulto-cordeiro-10kg",
      categoryId: "natural",
      name: "N&D Prime Adulto Cordeiro e Blueberry 10kg",
      brand: "N&D",
      lifeStage: "adult",
      sizeProfile: "medium",
      flavor: "Cordeiro e blueberry",
      priceCents: 32990,
      weightKg: 10,
      stock: 6,
      featured: true,
      active: true,
      imageUrl: "/store-app/assets/nd-prime-adulto-cordeiro-10kg.jpg",
      highlights: ["Baixo indice glicemico", "Sem graos", "Ingredientes selecionados"],
    },
    {
      id: "guabi-natural-mini-7_5kg",
      slug: "guabi-natural-mini-7-5kg",
      categoryId: "natural",
      name: "Guabi Natural Adulto Mini 7,5kg",
      brand: "Guabi Natural",
      lifeStage: "adult",
      sizeProfile: "mini",
      flavor: "Frango e arroz integral",
      priceCents: 15690,
      compareAtCents: 16990,
      weightKg: 7.5,
      stock: 14,
      featured: false,
      active: true,
      imageUrl: "/store-app/assets/guabi-natural-mini-7-5kg.jpg",
      highlights: ["Grao adaptado para porte pequeno", "Conservantes naturais", "Saude oral"],
    },
    {
      id: "hill-senior-large-12kg",
      slug: "hill-senior-large-12kg",
      categoryId: "premium-dry",
      name: "Hill's Science Diet Senior Large Breed 12kg",
      brand: "Hill's",
      lifeStage: "senior",
      sizeProfile: "large",
      flavor: "Frango",
      priceCents: 28990,
      weightKg: 12,
      stock: 7,
      featured: false,
      active: true,
      imageUrl: "/store-app/assets/hills-senior-large-12kg.jpg",
      highlights: ["Suporte articular", "Antioxidantes clinicamente comprovados", "Proteina magra"],
    },
    {
      id: "pedigree-carne-legumes-10kg",
      slug: "pedigree-carne-legumes-10kg",
      categoryId: "premium-dry",
      name: "Pedigree Adulto Carne e Legumes 10kg",
      brand: "Pedigree",
      lifeStage: "adult",
      sizeProfile: "all",
      flavor: "Carne e legumes",
      priceCents: 9990,
      compareAtCents: 10990,
      weightKg: 10,
      stock: 24,
      featured: false,
      active: true,
      imageUrl: "/store-app/assets/pedigree-carne-legumes-10kg.jpg",
      highlights: ["Custo-beneficio", "Fibras naturais", "Sabor palatavel"],
    },
    {
      id: "royal-canin-mini-puppy-8kg",
      slug: "royal-canin-mini-puppy-8kg",
      categoryId: "premium-dry",
      name: "Royal Canin Mini Puppy 8kg",
      brand: "Royal Canin",
      lifeStage: "puppy",
      sizeProfile: "mini",
      flavor: "Frango",
      priceCents: 23990,
      weightKg: 8,
      stock: 9,
      featured: true,
      active: true,
      imageUrl: "/store-app/assets/royal-canin-mini-puppy-8kg.jpg",
      highlights: ["Defesas naturais", "Croquete adaptado", "Digestao segura"],
    },
    {
      id: "granplus-gourmet-sache-frango-85g",
      slug: "granplus-gourmet-sache-frango-85g",
      categoryId: "wet-food",
      name: "GranPlus Gourmet Sache Frango 85g",
      brand: "GranPlus",
      lifeStage: "adult",
      sizeProfile: "all",
      flavor: "Frango",
      priceCents: 490,
      weightKg: 0.085,
      stock: 80,
      featured: false,
      active: true,
      imageUrl: "/store-app/assets/granplus-gourmet-sache-frango-85g.jpg",
      highlights: ["Textura umida", "Porcao individual", "Ideal para complementar"],
    },
  ],
  orders: [],
};
